# tomcat端口
server:
  port: 3000
spring:
  # 应用名称
  application:
    name: gateway
  # 数据源
  datasource:
    url: jdbc:mysql://localhost:3306/neti?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&allowMultiQueries=true
    hikari:
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        # 命名空间
        namespace: a6250d04-817d-42ea-b7e1-cae7ae055ca6
    gateway:
      discovery:
        locator:
          # 让gateway通过服务发现组件找到其他的微服务
          enabled: true
      routes:
        - id: user_route
          uri: lb://user-center
          predicates:
            - Path=/users/**,/tests/**

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
logging:
  level:
    org.springframework.cloud.gateway: trace