# tomcat端口
server:
  port: 4000
spring:
  application:
    name: cloud-admin
  # 数据源
  datasource:
    url: jdbc:mysql://localhost:3306/neti?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&allowMultiQueries=true
    hikari:
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        # 命名空间
        namespace: a6250d04-817d-42ea-b7e1-cae7ae055ca6
        # 集群名称 SZ
        cluster-name: SZ
        # 元数据
        metadata:
          instance: c
