# tomcat端口
server:
  port: 9001

spring:
  # 数据源
  datasource:
    url: jdbc:mysql://localhost:3306/neti?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&allowMultiQueries=true
    hikari:
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        # 指定nacos server的地址
        server-addr: localhost:8848
        # 命名空间
        namespace: a6250d04-817d-42ea-b7e1-cae7ae055ca6
        # 集群名称 SZ
        cluster-name: SZ
        # 元数据
        metadata:
          instance: c
    stream:
      rocketmq:
        binder:
          name-server: localhost:9876
      bindings:
        input:
          destination: stream-test-topic
          # 如果用的是rocketmq，这里一定要设置，如果是其它mq可留空
          group: binder-group
  # 服务名
  application:
    name: user-center

management:
  endpoint:
    web:
      exposure:
        include: '*'
# mybatis plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.teacherblitz.entity
# logging 配置
logging:
  level:
    com.teacherblitz.mapper: debug

# rocketmq
rocketmq:
  name-server: localhost:9876
